# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0008_auto_20160901_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='template_name',
            field=models.CharField(blank=True, help_text="Exemplo: 'flatpages/contact_page.html'. Se n\xe3o for informado, o sistema utilizar\xe1 o padr\xe3o 'staticpages/default.html'.", max_length=70, verbose_name='nome do template'),
        ),
    ]
