# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0009_auto_20160901_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='template_name',
            field=models.CharField(blank=True, help_text="Example: 'flatpages/contact_page.html'. If this isn't provided, the system will use 'staticpages/default.html'.", max_length=70, verbose_name='nome do template'),
        ),
    ]
