# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('template_name', models.CharField(blank=True, help_text="Example: 'yasp/contact_page.html'. If this isn't provided, the system will use 'yasp/default.html'.", max_length=70, verbose_name='template name')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('ordering', models.PositiveIntegerField(blank=True, null=True, verbose_name='ordering')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
            ],
            options={
                'ordering': ('ordering', '-updated_on'),
                'verbose_name': 'flat page',
                'verbose_name_plural': 'flat pages',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='flatpage',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yasp.Menu'),
        ),
    ]
