# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'menu', 'verbose_name_plural': 'menu'},
        ),
        migrations.AddField(
            model_name='flatpage',
            name='teaser',
            field=models.TextField(blank=True, null=True, verbose_name='teaser'),
        ),
    ]
