# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0002_auto_20160729_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='teaser',
            field=models.TextField(blank=True, default='', verbose_name='teaser'),
            preserve_default=False,
        ),
    ]
