# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0004_auto_20160801_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='t\xedtulo'),
        ),
    ]
