# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0005_auto_20160801_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpage',
            options={'ordering': ('ordering', '-updated_on'), 'verbose_name': 'p\xe1gina est\xe1tica', 'verbose_name_plural': 'p\xe1ginas est\xe1ticas'},
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='content',
            field=models.TextField(verbose_name='conte\xfado'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ordena\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='teaser',
            field=models.CharField(blank=True, max_length=140, verbose_name='pr\xe9via'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='template_name',
            field=models.CharField(blank=True, help_text="Exemplo: 'flatpages/contact_page.html'. Se n\xe3o for informado, o sistema utilizar\xe1 o padr\xe3o 'yasp/default.html'.", max_length=70, verbose_name='nome do template'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='t\xed\xadtulo'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
