# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 19:25
from __future__ import unicode_literals

from django.db import migrations, models

try:
    from filebrowser.fields import FileBrowseField as ImageField
except:
    ImageField = models.ImageField


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0010_auto_20160902_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='image',
            field=ImageField(blank=True, max_length=250, null=True, verbose_name='imagem'),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='link',
            field=models.CharField(blank=True, max_length=100, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='template_name',
            field=models.CharField(blank=True, help_text="Example: 'yasp/contact_page.html'. If this isn't provided, the system will use 'yasp/default.html'.", max_length=70, verbose_name='nome do template'),
        ),
    ]
