# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0011_auto_20160902_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='link'),
        ),
    ]
