# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0012_auto_20160902_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='content',
            field=models.TextField(blank=True, verbose_name='conte\xfado'),
        ),
    ]
