# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0015_auto_20160926_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpage',
            options={'ordering': ('ordering',), 'verbose_name': 'flat page', 'verbose_name_plural': 'flat pages'},
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='yasp.Menu', verbose_name='menu'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='teaser',
            field=models.CharField(blank=True, max_length=140, verbose_name='teaser'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='template_name',
            field=models.CharField(blank=True, help_text="Example: 'yasp/contact_page.html'. If this isn't provided, the system will use 'yasp/default.html'.", max_length=70, verbose_name='template name'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='t\xedtulo'),
        ),
    ]
