# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasp', '0017_auto_20160926_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='flatpages/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='updated on'),
        ),
    ]
